databases:
  - name: code-auditor-db
    databaseName: code_auditor
    user: code_auditor
    plan: free

services:
  - type: web
    name: code-auditor-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/audit/providers
    plan: free
    envVars:
      - key: DB_URL
        fromDatabase:
          name: code-auditor-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: APP_FRONTEND_URL
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false

  - type: static
    name: code-auditor-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
    envVars:
      - key: VITE_API_URL
        sync: false
